config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  get "products", to: "products#index", as: "products"

  root to: "static_pages#home"
  get "about", to: "static_pages#about", as: "about"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
        redirect_to checkout_payment_path
      end
    end
  end

  def payment
    if request.post?
      redirect_to checkout_confirmation_path
    end
  end

  def confirmation
    if request.post?
      binding.pry
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Order has been placed successfully!"
    end
  end

  def destroy
    current_order.destroy
    session[:order_id] = nil
    redirect_to root_path, :notice => "Basket emptied successfully."
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def home
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
  end

  def index
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
  end

  def show
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
  end

  def buy
    @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
    current_order.order_items.add_item(@product, 1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.haml
- if current_order
  %p{:style => "border:1px solid black;padding:10px;"}
    You have #{pluralize current_order.total_items, 'item'} in your basket which cost
    \#{number_to_currency current_order.total_before_tax}.
    = link_to "View basket", basket_path
    = link_to "Checkout", checkout_path
    = flash[:notice]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JellySelly
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %header
    / Navigation
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        %a.navbar-brand{:href => "/"} JellySelly
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li.page-scroll
              %a{:href => "/shoppe/login"} JellySelly Admin
            %li.page-scroll
              %a{:href => "/products"} Products
            %li.page-scroll
              %a{:href => "/basket"} Basket
        / /.navbar-collapse
      / /.container-fluid
    = yield

app/views/orders/_items.html.haml
%table{:border => "1", :width => "100%", :class => "table table-striped"}
  %thead
    %tr
      %td Quantity
      %td Product
      %td Sub-Total
      %td Tax
      %td Total
  %tbody
    - order.order_items.each do |item|
      %tr
        %td= item.quantity
        %td= item.ordered_item.full_name
        %td= number_to_currency item.sub_total
        %td= number_to_currency item.tax_amount
        %td= number_to_currency item.total
    - if order.delivery_service
      %tr
        %td
        %td= order.delivery_service.name
        %td= number_to_currency order.delivery_price
        %td= number_to_currency order.delivery_tax_amount
        %td= number_to_currency order.delivery_price + order.delivery_tax_amount
  %tfoot
    %tr
      %td{:colspan => "4"} Sub-Total
      %td= number_to_currency order.total_before_tax
    %tr
      %td{:colspan => "4"} Tax
      %td= number_to_currency order.tax
    %tr
      %td{:colspan => "4"} Total
      %td= number_to_currency order.total

app/views/orders/checkout.html.haml
.container
  %h2 Checkout
  = render 'items', :order => @order
  = form_for @order, :url => checkout_path do |f|
    %dl
      %dt= f.label :first_name, 'Name'
      %dd
        = f.text_field :first_name
        = f.text_field :last_name
      %dt= f.label :billing_address1, 'Address'
      %dd= f.text_field :billing_address1
      %dd= f.text_field :billing_address2
      %dd= f.text_field :billing_address3
      %dd= f.text_field :billing_address4
      %dt= f.label :billing_postcode, 'Post code'
      %dd= f.text_field :billing_postcode
      %dd= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true
      %dt= f.label :email_address
      %dd= f.text_field :email_address
      %dt= f.label :phone_number
      %dd= f.text_field :phone_number
      %br
      %dd= f.submit 'Continue', :class => "btn btn-secondary"

app/views/orders/confirmation.html.haml
.container
  %h2 Place your order
  = render 'items', :order => current_order
  = button_to "Place order", :class => "btn btn-secondary"

app/views/orders/payment.html.haml
.container
  %h2 Make your payment
  = form_tag do
    %dl
      %dt= label_tag 'card_number'
      %dd= text_field_tag 'card_number'
      %dt= label_tag 'expiry'
      %dd= text_field_tag 'expiry'
      %dt= label_tag 'security_code'
      %dd= text_field_tag 'security_code'
      %dd= submit_tag "Continue", :class => "btn btn-success"

app/views/orders/show.html.haml
.container
  %h2 Your basket
  = render 'items', :order => current_order

  %p= button_to 'Empty basket', basket_path, :method => :delete, :class => "btn btn-secondary"

app/views/products/index.html.haml
.container
  %br
  %br
  %br
  = render "layouts/footer"
  %h2 Shop by Category
  - @products.each do |category, products|
    %h3= category.name
    %ul{class: "list-group"}
      - products.each do |product|
        %li{class: "list-group-item"}
          %h4= link_to product.name, product_path(product.permalink)
          %p= product.short_description
          %p
            %b Price:
            = number_to_currency product.price

app/views/products/show.html.haml
.container
  %br
  %br
  %br
  = render "layouts/footer"
  %h2= @product.name
  - if @product.default_image
    = image_tag @product.default_image.path, :width => '200px', :style => "float:right"
  %p= @product.short_description
  %p
    %b= number_to_currency @product.price
    = button_to "Add to basket", product_path(@product.permalink), :method => :post, :class => "btn btn-primary"
  %hr
    = simple_format @product.description
    %hr
      %p= button_to "Back to list", products_path, method: :get, :class => "btn btn-secondary"

app/views/static_pages/home.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %meta{:content => "", :name => "description"}
            %meta{:content => "", :name => "author"}
              %title JellySelly
    / Header
    %header
      .container
        - 5.times do
          %br
        %img{:src => asset_path("jellyselly.png"), :class => "img-responsive center-block"}/
        .row
          .col-lg-12
          %h2 Shop by Category
          - @products.each do |category, products|
            %h3= category.name
            %ul{class: "list-group"}
              - products.each do |product|
                %li{class: "list-group-item"}
                  %h4= link_to product.name, product_path(product.permalink)
                  %p= product.short_description
                  %p
                    %b Price:
                    = number_to_currency product.price
    / Contact Section
    %section#contact
      .container
        .row
          .col-lg-12.text-center
            %h2 Contact JellySelly
            %hr.star-primary
        .row
          .col-lg-8.col-lg-offset-2
            / To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.
            / The form should work on most web servers, but if the form is not working you may need to configure your web server differently.
            %form#contactForm{:name => "sentMessage", :novalidate => ""}
              .row.control-group
                .form-group.col-xs-12.floating-label-form-group.controls
                  %label Name
                  %input#name.form-control{"data-validation-required-message" => "Please enter your name.", :placeholder => "Name", :required => "", :type => "text"}
                    %p.help-block.text-danger
              .row.control-group
                .form-group.col-xs-12.floating-label-form-group.controls
                  %label Email Address
                  %input#email.form-control{"data-validation-required-message" => "Please enter your email address.", :placeholder => "Email Address", :required => "", :type => "email"}
                    %p.help-block.text-danger
              .row.control-group
                .form-group.col-xs-12.floating-label-form-group.controls
                  %label Phone Number
                  %input#phone.form-control{"data-validation-required-message" => "Please enter your phone number.", :placeholder => "Phone Number", :required => "", :type => "tel"}
                    %p.help-block.text-danger
              .row.control-group
                .form-group.col-xs-12.floating-label-form-group.controls
                  %label Message
                  %textarea#message.form-control{"data-validation-required-message" => "Please enter a message.", :placeholder => "Message", :required => "", :rows => "5"}
                  %p.help-block.text-danger
              %br
                #success
                .row
                  .form-group.col-xs-12
                    %button.btn.btn-success.btn-lg{:type => "submit"} Send